// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// Load .env.local first (Next.js convention), then fall back to .env
import { config } from "dotenv";
config({ path: ".env.local" });
config(); // .env fallback
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Prisma CLI migrations always run against the local SQLite file.
    // The runtime adapter (in lib/prisma.ts) connects to Turso via libsql://.
    url: "file:./dev.db",
  },
});
